---
title: "Main Analysis"
author: "Martin Braquet, Riki Dewan"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    toc_float: true
    theme: lumen
    code_folding: show
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo       = TRUE,
  warning    = FALSE,
  message    = FALSE,
  fig.width  = 9,
  fig.height = 6,
  dpi        = 300,
  cache      = TRUE
)

library(tidyverse)
library(brms)
library(here)

# Load specialized utility functions
source(here("analysis", "utils", "model.R"))
source(here("analysis", "utils", "sim.R"))
source(here("analysis", "utils", "plotting.R"))
source(here("analysis", "utils", "power.R"))
source(here("analysis", "utils", "stop_criteria.R"))
source(here("analysis", "utils", "sensitivity.R"))

set.seed(42)
```

## Purpose

The main analysis checks the stopping conditions with the current data and assigns the recommended preparation to the resolved children.

```{r}
file_path <- here("data", "study_data.csv")
study_data <- read_csv(file_path)

study_data <- study_data %>%
  mutate(
    baseline_state = factor(baseline_state, levels = c("tired", "neutral", "hyper")),
    prep = factor(prep, levels = c("No Prep", "Calming", "Stimulating", "Child Choice")),
    child_id = as.factor(child_id)
  )
study_data
```

```{r}
chains <- 4
fit <- fit_model_fresh(
  study_data,
  threads = threading(chains),
  chains = chains,
  iter = 2000
)
summary(fit)
```

```{r}
chains <- 4
results <- check_stopping_sequentially(
  template_fit = fit,
  data = study_data,
  min_sessions = 0
)
child_status <- results$child_status
child_status
```
