name: GitHub Release

# Must select "Read and write permissions" in GitHub → Repo → Settings → Actions → General → Workflow permissions

on:
  push:
    branches: [main, master]
    paths:
      - 'package.json'
      - '.github/workflows/cd.yml'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@master
        with:
          fetch-depth: 0 # To fetch all history for tags

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Tag and release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          ./scripts/release.sh
